import type { Repo, Report, TeamMember } from "./types"

export const mockRepos: Repo[] = [
  {
    id: "1",
    name: "frontend-app",
    complianceScore: 89,
    status: "healthy",
    lastAudit: "2024-01-15",
    violations: [
      {
        id: "v1",
        type: "Missing Code Review",
        severity: "medium",
        description: "Pull request #123 was merged without required code review",
        suggestedFix: "Enable branch protection rules requiring at least 2 reviewers",
        date: "2024-01-14",
        resolved: false,
      },
      {
        id: "v2",
        type: "Hardcoded Secret",
        severity: "high",
        description: "API key found in commit abc123",
        suggestedFix: "Remove secret from code and use environment variables",
        date: "2024-01-13",
        resolved: true,
      },
    ],
  },
  {
    id: "2",
    name: "backend-api",
    complianceScore: 76,
    status: "at-risk",
    lastAudit: "2024-01-14",
    violations: [
      {
        id: "v3",
        type: "CI Logging Disabled",
        severity: "medium",
        description: "CI pipeline lacks comprehensive logging",
        suggestedFix: "Add logging configuration to .gitlab-ci.yml",
        date: "2024-01-12",
        resolved: false,
      },
      {
        id: "v4",
        type: "Dependency Vulnerability",
        severity: "high",
        description: "High severity vulnerability in lodash@4.17.20",
        suggestedFix: "Update lodash to version 4.17.21 or higher",
        date: "2024-01-11",
        resolved: false,
      },
    ],
  },
  {
    id: "3",
    name: "mobile-app",
    complianceScore: 45,
    status: "non-compliant",
    lastAudit: "2024-01-13",
    violations: [
      {
        id: "v5",
        type: "No Branch Protection",
        severity: "high",
        description: "Main branch allows direct pushes without review",
        suggestedFix: "Enable branch protection rules for main branch",
        date: "2024-01-10",
        resolved: false,
      },
      {
        id: "v6",
        type: "Missing Tests",
        severity: "medium",
        description: "Code coverage below 50% threshold",
        suggestedFix: "Add unit tests to increase coverage above 80%",
        date: "2024-01-09",
        resolved: false,
      },
      {
        id: "v7",
        type: "Exposed Credentials",
        severity: "high",
        description: "Database password found in configuration file",
        suggestedFix: "Move credentials to secure environment variables",
        date: "2024-01-08",
        resolved: false,
      },
    ],
  },
  {
    id: "4",
    name: "data-pipeline",
    complianceScore: 92,
    status: "healthy",
    lastAudit: "2024-01-15",
    violations: [
      {
        id: "v8",
        type: "Outdated Dependencies",
        severity: "low",
        description: "Several dependencies are 6+ months old",
        suggestedFix: "Update dependencies to latest stable versions",
        date: "2024-01-07",
        resolved: false,
      },
    ],
  },
  {
    id: "5",
    name: "documentation",
    complianceScore: 67,
    status: "at-risk",
    lastAudit: "2024-01-12",
    violations: [
      {
        id: "v9",
        type: "Missing Security Policy",
        severity: "medium",
        description: "Repository lacks SECURITY.md file",
        suggestedFix: "Add SECURITY.md file with vulnerability reporting process",
        date: "2024-01-06",
        resolved: false,
      },
      {
        id: "v10",
        type: "Insufficient Documentation",
        severity: "low",
        description: "README.md lacks setup and contribution guidelines",
        suggestedFix: "Expand README with detailed setup and contribution instructions",
        date: "2024-01-05",
        resolved: false,
      },
    ],
  },
  {
    id: "6",
    name: "infrastructure",
    complianceScore: 84,
    status: "healthy",
    lastAudit: "2024-01-14",
    violations: [
      {
        id: "v11",
        type: "Terraform State Security",
        severity: "medium",
        description: "Terraform state file contains sensitive data",
        suggestedFix: "Enable state file encryption and remote backend",
        date: "2024-01-04",
        resolved: true,
      },
    ],
  },
  {
    id: "70888017",
    name: "audit-flow-sample-repo-2",
    complianceScore: 94,
    status: "healthy",
    lastAudit: "2025-06-17",
    violations: [
      {
        id: "v100",
        type: "Missing Audit Logging",
        severity: "high",
        description: "No audit logging middleware detected in production config.",
        suggestedFix: "Add audit logging middleware to Next.js API routes.",
        date: "2025-06-17",
        resolved: false,
      },
      {
        id: "v101",
        type: "Unused Import",
        severity: "low",
        description: "Unused import 'Html' in pages/_document.tsx.",
        suggestedFix: "Remove unused import to clean up code.",
        date: "2025-06-17",
        resolved: false,
      },
      {
        id: "v102",
        type: "Hardcoded Secret",
        severity: "high",
        description: "API key found in next.config.mjs.",
        suggestedFix: "Move secrets to environment variables.",
        date: "2025-06-17",
        resolved: false,
      },
      {
        id: "v103",
        type: "Missing CSP",
        severity: "medium",
        description: "No Content Security Policy set in _document.tsx.",
        suggestedFix: "Add CSP meta tag for enhanced security.",
        date: "2025-06-17",
        resolved: false,
      },
      {
        id: "v104",
        type: "No HTTPS Redirect",
        severity: "medium",
        description: "App does not enforce HTTPS in production.",
        suggestedFix: "Add HTTPS redirect middleware.",
        date: "2025-06-17",
        resolved: false,
      },
      {
        id: "v105",
        type: "Exposed .env File",
        severity: "high",
        description: ".env file is accessible from the public directory.",
        suggestedFix: "Ensure .env files are not exposed in public/.",
        date: "2025-06-17",
        resolved: false,
      },
      {
        id: "v106",
        type: "Missing Helmet",
        severity: "medium",
        description: "No helmet or similar security headers middleware detected.",
        suggestedFix: "Add helmet or next-secure-headers.",
        date: "2025-06-17",
        resolved: false,
      },
      {
        id: "v107",
        type: "No Rate Limiting",
        severity: "medium",
        description: "API routes lack rate limiting.",
        suggestedFix: "Implement rate limiting for API endpoints.",
        date: "2025-06-17",
        resolved: false,
      },
      {
        id: "v108",
        type: "Missing Sentry Integration",
        severity: "low",
        description: "No error monitoring (Sentry) integration found.",
        suggestedFix: "Add Sentry or similar error monitoring.",
        date: "2025-06-17",
        resolved: false,
      },
      {
        id: "v109",
        type: "No Static Code Analysis",
        severity: "low",
        description: "No static code analysis (ESLint) configured.",
        suggestedFix: "Add ESLint and configure for Next.js.",
        date: "2025-06-17",
        resolved: false,
      },
      {
        id: "v110",
        type: "Missing Unit Tests",
        severity: "medium",
        description: "No unit tests found for critical components.",
        suggestedFix: "Add unit tests using Jest or similar.",
        date: "2025-06-17",
        resolved: false,
      },
      {
        id: "v111",
        type: "No 2FA for Admins",
        severity: "medium",
        description: "Admin users do not have 2FA enforced.",
        suggestedFix: "Require 2FA for all admin accounts.",
        date: "2025-06-17",
        resolved: false,
      },
      {
        id: "v112",
        type: "Outdated Dependency",
        severity: "low",
        description: "next-auth dependency is outdated.",
        suggestedFix: "Update next-auth to the latest version.",
        date: "2025-06-17",
        resolved: false,
      },
    ],
  },
]

export const mockReports: Report[] = [
  {
    id: "1",
    title: "Q2 2025 SOC 2 Compliance Report",
    repository: "frontend-app",
    framework: "SOC2",
    formats: ["PDF", "Markdown"],
    status: "completed",
    generatedDate: "2025-06-17",
    preview: "Executive Summary: This report covers SOC 2 Type II compliance assessment for Q2 2025, highlighting recent improvements and remaining issues in the frontend-app repository.",
  },
  {
    id: "2",
    title: "HIPAA Security Assessment 2025",
    repository: "backend-api",
    framework: "HIPAA",
    formats: ["PDF", "Google Doc"],
    status: "completed",
    generatedDate: "2025-06-15",
    preview: "Healthcare data protection compliance analysis for backend-api, focusing on HIPAA requirements and recent remediation steps as of June 2025.",
  },
  {
    id: "3",
    title: "ISO 27001 Annual Review 2025",
    repository: "data-pipeline",
    framework: "ISO27001",
    formats: ["PDF"],
    status: "in-progress",
    generatedDate: "2025-06-12",
    preview: "Information security management system assessment for data-pipeline, with a focus on ISO 27001 controls and June 2025 audit findings.",
  },
  {
    id: "4",
    title: "Custom Security Framework Audit (June 2025)",
    repository: "mobile-app",
    framework: "Custom",
    formats: ["Markdown", "PDF"],
    status: "completed",
    generatedDate: "2025-06-10",
    preview: "Custom security controls and compliance verification for mobile-app, including new findings and recommendations as of June 2025.",
  },
  {
    id: "5",
    title: "SOC 2 Quarterly Check (May 2025)",
    repository: "infrastructure",
    framework: "SOC2",
    formats: ["PDF"],
    status: "failed",
    generatedDate: "2025-05-29",
    preview: "Quarterly compliance verification for infrastructure failed due to missing controls and unresolved issues as of May 2025.",
  },
]

export const mockTeamMembers: TeamMember[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@company.com",
    role: "Admin",
    accessedRepos: ["frontend-app", "backend-api", "mobile-app"],
    lastLogin: "2024-01-15",
    status: "active",
  },
  {
    id: "2",
    name: "Sarah Wilson",
    email: "sarah.wilson@company.com",
    role: "Auditor",
    accessedRepos: ["backend-api", "data-pipeline"],
    lastLogin: "2024-01-14",
    status: "active",
  },
  {
    id: "3",
    name: "Mike Chen",
    email: "mike.chen@company.com",
    role: "Viewer",
    accessedRepos: ["frontend-app"],
    lastLogin: "2024-01-13",
    status: "active",
  },
  {
    id: "4",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@company.com",
    role: "Auditor",
    accessedRepos: ["infrastructure", "mobile-app"],
    lastLogin: "2024-01-12",
    status: "pending",
  },
  {
    id: "5",
    name: "David Kim",
    email: "david.kim@company.com",
    role: "Viewer",
    accessedRepos: ["documentation"],
    lastLogin: "2024-01-10",
    status: "inactive",
  },
]
